import { ROLES } from "../constants";

export const USER_PROFILES: any = {
  "freelancer_1@gmail.com": {
    id: 1,
    email: "freelancer_1@gmail.com",
    password: "12345",
    role: ROLES.FREELANCER,
  },
  "freelancer_2@gmail.com": {
    id: 2,
    email: "freelancer_2@gmail.com",
    password: "12345",
    role: ROLES.FREELANCER,
  },
  "freelancer_3@gmail.com": {
    id: 3,
    email: "freelancer_3@gmail.com",
    password: "12345",
    role: ROLES.FREELANCER,
  },
  "employer_1@gmail.com": {
    id: 1,
    name: "employer_1",
    email: "employer_1@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "9876789098",
    company_name: "Adobe",
    password: "12345",
  },
  "employer_7@gmail.com": {
    id: 7,
    name: "employer_7",
    email: "employer_7@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678907",
    company_name: "Twitter",
    password: "12345",
  },
  "employer_2@gmail.com": {
    id: 2,
    name: "employer_2",
    email: "employer_2@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "6787654567",
    company_name: "Google",
    password: "12345",
  },
  "employer_6@gmail.com": {
    id: 6,
    name: "employer_6",
    email: "employer_6@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678906",
    company_name: "Amazon",
    password: "12345",
  },
  "employer_5@gmail.com": {
    id: 5,
    name: "employer_5",
    email: "employer_5@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678905",
    company_name: "Netflix",
    password: "12345",
  },
  "employer_9@gmail.com": {
    id: 9,
    name: "employer_9",
    email: "employer_9@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678909",
    company_name: "Spotify",
    password: "12345",
  },
  "employer_10@gmail.com": {
    id: 10,
    name: "employer_10",
    email: "employer_10@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678910",
    company_name: "Uber",
    password: "12345",
  },
  "employer_11@gmail.com": {
    id: 11,
    name: "employer_11",
    email: "employer_11@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678911",
    company_name: "Airbnb",
    password: "12345",
  },
  "employer_12@gmail.com": {
    id: 12,
    name: "employer_12",
    email: "employer_12@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678912",
    company_name: "Intuit",
    password: "12345",
  },
  "employer_3@gmail.com": {
    id: 3,
    name: "employer_3",
    email: "employer_3@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678909",
    company_name: "Paytm",
    password: "12345",
  },
  "employer_4@gmail.com": {
    id: 4,
    name: "employer_4",
    email: "employer_4@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "7656786746",
    company_name: "Microsoft",
    password: "12345",
  },
  "employer_8@gmail.com": {
    id: 8,
    name: "employer_8",
    email: "employer_8@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678908",
    company_name: "Netflix",
    password: "12345",
  },
  "employer_13@gmail.com": {
    id: 13,
    name: "employer_13",
    email: "employer_13@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678913",
    company_name: "Slack",
    password: "12345",
  },
  "employer_14@gmail.com": {
    id: 14,
    name: "employer_14",
    email: "employer_14@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678914",
    company_name: "Salesforce",
    password: "12345",
  },
  "employer_15@gmail.com": {
    id: 15,
    name: "employer_15",
    email: "employer_15@gmail.com",
    role: ROLES.EMPLOYER,
    contact_no: "8765678915",
    company_name: "Tesla",
    password: "12345",
  },
};
