export const mockJobs: any = [
  {
    id: 1,
    jobTitle: "Software Development Engineer III",
    companyName: "Amazon",
    ratePerHour: "$52",
    skills: ["React", "Javascript", "Vue", "Angular", "HTML"],
    email: "euismod.urna@icloud.net",
  },
  {
    id: 2,
    jobTitle: "Senior Software Engineer",
    companyName: "Walmart",
    ratePerHour: "$127",
    skills: ["React", "Javascript", "Vue", "Angular", "HTML"],
    email: "risus@icloud.net",
  },
  {
    id: 3,
    jobTitle: "Software Engineer II",
    companyName: "Amazon",
    ratePerHour: "$52",
    skills: ["React", "Javascript", "Vue", "Angular", "HTML"],
    email: "euismod.urna@icloud.net",
  },
  {
    id: 4,
    jobTitle: "Software Engineer",
    companyName: "Walmart",
    ratePerHour: "$127",
    skills: ["React", "Javascript", "Vue", "Angular", "HTML"],
    email: "risus@icloud.net",
  },
  {
    id: 5,
    jobTitle: "semper egestas,",
    companyName: "Aliquet Molestie Associates",
    ratePerHour: "$61",
    skills: ["DKK", "EUR", "EUR"],
    email: "sed.pede@hotmail.net",
  },
  {
    id: 6,
    jobTitle: "eleifend. Cras",
    companyName: "Nulla Ante Iaculis LLP",
    ratePerHour: "$112",
    skills: ["XOF", "ALL", "NAD", "INR"],
    email: "suspendisse.aliquet@aol.org",
  },
  {
    id: 7,
    jobTitle: "tristique ac, eleifend",
    companyName: "Lacus Etiam PC",
    ratePerHour: "$95",
    skills: ["CNY", "SGD", "EUR", "OMR", "JOD", "USD", "CVE", "AUD"],
    email: "pellentesque.ultricies@icloud.org",
  },
  {
    id: 8,
    jobTitle: "Pellentesque",
    companyName: "In Dolor Company",
    ratePerHour: "$144",
    skills: ["USD", "PLN", "UGX", "PGK", "TMT", "UZS", "MUR"],
    email: "nulla.aliquet@icloud.ca",
  },
  {
    id: 9,
    jobTitle: "egestas lacinia.",
    companyName: "Sed Dui Corp.",
    ratePerHour: "$55",
    skills: ["JOD", "BGN", "BHD", "PHP"],
    email: "arcu@hotmail.org",
  },
  {
    id: 10,
    jobTitle: "neque.",
    companyName: "Nec Enim Institute",
    ratePerHour: "$55",
    skills: ["EUR", "USD", "DKK", "EUR", "'XOF", "XAF", "GTQ", "EUR"],
    email: "vitae@icloud.com",
  },
  {
    id: 11,
    jobTitle: "velit. Sed",
    companyName: "Mauris Elit Dictum Incorporated",
    ratePerHour: "$108",
    skills: ["XAF", "JPY", "EUR", "VND", "XOF"],
    email: "odio.aliquam@protonmail.org",
  },
  {
    id: 12,
    jobTitle: "risus. Nulla eget",
    companyName: "Leo In Associates",
    ratePerHour: "$126",
    skills: ["SEK", "RUB", "CRC", "TZS", "USD"],
    email: "sociis.natoque@icloud.ca",
  },
  {
    id: 13,
    jobTitle: "magna, malesuada",
    companyName: "Nec Tempus Mauris Company",
    ratePerHour: "$131",
    skills: ["RSD", "PYG", "'EUR"],
    email: "risus.duis@hotmail.couk",
  },
  {
    id: 14,
    jobTitle: "Nunc",
    companyName: "Lobortis Augue Ltd",
    ratePerHour: "$64",
    skills: ["EUR", "USD", "BWP", "ARS", "EUR", "EUR"],
    email: "aliquam@aol.ca",
  },
  {
    id: 15,
    jobTitle: "orci, consectetuer",
    companyName: "Metus Aenean Institute",
    ratePerHour: "$78",
    skills: ["GEL", "TJS", "'CZK", "'XOF", "EUR", "ISK", "JMD", "EUR"],
    email: "aliquam.ornare@yahoo.net",
  },
  {
    id: 16,
    jobTitle: "faucibus id,",
    companyName: "Non Cursus Corporation",
    ratePerHour: "$96",
    skills: ["RUB", "ARS", "BWP", "XAF", "USD", "SGD", "NIO", "ILS", "DZD"],
    email: "tincidunt@aol.couk",
  },
  {
    id: 17,
    jobTitle: "Cras dictum ultricies",
    companyName: "Mauris Elit LLC",
    ratePerHour: "$123",
    skills: ["INR", "MOP", "NAD", "IDR", "XOF"],
    email: "aliquam.gravida@icloud.ca",
  },
  {
    id: 18,
    jobTitle: "risus",
    companyName: "Massa Inc.",
    ratePerHour: "$118",
    skills: ["ARS", "KWD", "CHF", "TRY", "MGA", "KGS", "XAF", "ILS", "BWP"],
    email: "eleifend@yahoo.edu",
  },
  {
    id: 19,
    jobTitle: "turpis egestas.",
    companyName: "Nascetur Ridiculus LLP",
    ratePerHour: "$79",
    skills: ["BRL", "EUR", "MYR", "KHR", "RUB", "MOP"],
    email: "pede.praesent.eu@outlook.couk",
  },
  {
    id: 20,
    jobTitle: "fermentum metus.",
    companyName: "Ipsum Nunc Associates",
    ratePerHour: "$133",
    skills: ["NZD", "PGK", "USD", "GBP", "EUR"],
    email: "pede@icloud.org",
  },
  {
    id: 21,
    jobTitle: "risus varius",
    companyName: "Nunc Mauris Elit Inc.",
    ratePerHour: "$119",
    skills: ["LAK", "RON", "VEF", "EUR", "MUR", "CRC", "BWP"],
    email: "vitae.velit@protonmail.ca",
  },
  {
    id: 22,
    jobTitle: "Phasellus at",
    companyName: "Id LLP",
    ratePerHour: "$133",
    skills: ["EUR", "MRU", "EUR", "BOB", "BAM", "NGN", "ZMW"],
    email: "turpis.egestas@aol.net",
  },
  {
    id: 23,
    jobTitle: "sit",
    companyName: "Scelerisque Corp.",
    ratePerHour: "$97",
    skills: ["EUR", "PHP", "KWD", "EGP", "SAR", "QAR", "EUR", "KYD", "THB"],
    email: "mollis.lectus@aol.couk",
  },
  {
    id: 24,
    jobTitle: "dis parturient montes,",
    companyName: "Congue A Aliquet Corp.",
    ratePerHour: "$95",
    skills: ["PEN", "GBP", "IQD", "BOB", "JOD"],
    email: "mollis@google.com",
  },
  {
    id: 25,
    jobTitle: "sit amet, dapibus",
    companyName: "Vitae Aliquam Incorporated",
    ratePerHour: "$130",
    skills: ["'XOF", "EUR", "HNL", "SZL", "MDL", "GTQ", "ZAR"],
    email: "lectus.cum.sociis@protonmail.com",
  },
  {
    id: 26,
    jobTitle: "Cras dolor dolor,",
    companyName: "Mauris Industries",
    ratePerHour: "$116",
    skills: ["PKR", "'XOF", "NGN", "EUR"],
    email: "nonummy@icloud.org",
  },
  {
    id: 27,
    jobTitle: "quis, pede.",
    companyName: "A Felis Ullamcorper Associates",
    ratePerHour: "$133",
    skills: ["HRK", "XCD", "KRW", "EUR", "EUR"],
    email: "sed.eu.nibh@google.ca",
  },
  {
    id: 28,
    jobTitle: "velit. Sed",
    companyName: "Adipiscing Corp.",
    ratePerHour: "$128",
    skills: ["'MMK", "EUR", "KGS"],
    email: "a.neque.nullam@icloud.ca",
  },
  {
    id: 29,
    jobTitle: "mi",
    companyName: "Ad Litora Ltd",
    ratePerHour: "$119",
    skills: ["USD", "BYN", "RON", "BMD", "CDF", "TZS", "CRC", "MAD", "AUD"],
    email: "nec@protonmail.edu",
  },
  {
    id: 30,
    jobTitle: "iaculis,",
    companyName: "Quam Corp.",
    ratePerHour: "$69",
    skills: ["NAD", "TND", "EUR", "MOP", "MRU", "KRW", "LYD", "XAF"],
    email: "donec.egestas.aliquam@outlook.com",
  },
  {
    id: 31,
    jobTitle: "Donec",
    companyName: "Enim Corporation",
    ratePerHour: "$145",
    skills: ["BBD", "BYN", "TWD", "EUR"],
    email: "ac.fermentum@protonmail.org",
  },
  {
    id: 32,
    jobTitle: "lectus ante",
    companyName: "Nulla Vulputate Ltd",
    ratePerHour: "$108",
    skills: ["MVR", "GBP", "UAH", "TWD"],
    email: "sapien@aol.edu",
  },
  {
    id: 33,
    jobTitle: "aliquet,",
    companyName: "Tellus Incorporated",
    ratePerHour: "$87",
    skills: ["DKK", "EUR", "CDF", "TND"],
    email: "donec.sollicitudin@yahoo.net",
  },
  {
    id: 34,
    jobTitle: "nonummy ut,",
    companyName: "Litora Torquent Corporation",
    ratePerHour: "$52",
    skills: ["KZT", "COP", "RWF", "GBP", "EUR", "ISK", "EUR"],
    email: "duis@yahoo.ca",
  },
  {
    id: 35,
    jobTitle: "eu, odio.",
    companyName: "Vel Institute",
    ratePerHour: "$50",
    skills: ["EUR", "DOP", "RWF", "BMD", "XCD"],
    email: "nec.ligula@google.net",
  },
  {
    id: 36,
    jobTitle: "vel pede blandit",
    companyName: "Non Massa Industries",
    ratePerHour: "$75",
    skills: ["BRL", "'EUR", "IQD", "ZAR", "THB", "EUR", "BHD", "XAF"],
    email: "tellus.eu.augue@outlook.net",
  },
  {
    id: 37,
    jobTitle: "sed, hendrerit",
    companyName: "Aliquam Adipiscing LLC",
    ratePerHour: "$126",
    skills: ["XAF", "ALL", "NOK", "KES", "ZAR", "EUR"],
    email: "elementum.at.egestas@protonmail.org",
  },
  {
    id: 38,
    jobTitle: "mollis.",
    companyName: "Fusce Feugiat Ltd",
    ratePerHour: "$104",
    skills: ["ZAR", "LYD", "RWF", "PKR", "BBD", "GBP", "USD", "EUR"],
    email: "in.nec@outlook.org",
  },
  {
    id: 39,
    jobTitle: "vitae diam.",
    companyName: "Nonummy Company",
    ratePerHour: "$128",
    skills: ["NAD", "MGA", "USD", "MRU", "AUD", "DZD"],
    email: "quam.dignissim.pharetra@outlook.edu",
  },
  {
    id: 40,
    jobTitle: "arcu. Sed et",
    companyName: "Augue Eu Inc.",
    ratePerHour: "$109",
    skills: ["XAF", "COP", "IDR", "EUR"],
    email: "ullamcorper.nisl@icloud.net",
  },
  {
    id: 41,
    jobTitle: "ut,",
    companyName: "Mollis Non Industries",
    ratePerHour: "$116",
    skills: [
      "HNL",
      "MXN",
      "RON",
      "KZT",
      "PLN",
      "NGN",
      "FJD",
      "AOA",
      "COP",
      "PYG",
    ],
    email: "a@google.net",
  },
  {
    id: 42,
    jobTitle: "nec orci.",
    companyName: "Vel Arcu Inc.",
    ratePerHour: "$102",
    skills: ["KRW", "ILS", "KHR", "GYD"],
    email: "a.scelerisque.sed@google.ca",
  },
  {
    id: 43,
    jobTitle: "vitae, sodales at,",
    companyName: "Tellus Inc.",
    ratePerHour: "$72",
    skills: [
      "HKD",
      "KRW",
      "INR",
      "EUR",
      "CNY",
      "TTD",
      "MNT",
      "KWD",
      "LBP",
      "MDL",
    ],
    email: "lorem.fringilla@aol.com",
  },
  {
    id: 44,
    jobTitle: "Cras eget",
    companyName: "Ullamcorper Viverra Corporation",
    ratePerHour: "$105",
    skills: ["EUR", "KGS", "MXN", "RUB", "USD", "TWD"],
    email: "facilisis.eget@aol.edu",
  },
  {
    id: 45,
    jobTitle: "congue. In scelerisque",
    companyName: "Justo Eu Foundation",
    ratePerHour: "$144",
    skills: ["USD", "ILS", "TWD", "XAF", "'XOF", "ARS", "'EUR", "USD"],
    email: "dui@icloud.net",
  },
  {
    id: 46,
    jobTitle: "in, tempus eu,",
    companyName: "Dictum Placerat LLP",
    ratePerHour: "$138",
    skills: ["QAR", "HNL", "XAF", "EUR", "COP", "EUR", "EUR", "SGD", "EUR"],
    email: "auctor@protonmail.ca",
  },
  {
    id: 47,
    jobTitle: "nunc ac",
    companyName: "Nullam Suscipit Est LLC",
    ratePerHour: "$106",
    skills: ["GIP", "MAD", "EUR", "EGP", "XCD", "MYR", "TWD", "MWK", "PLN"],
    email: "magna@aol.ca",
  },
  {
    id: 48,
    jobTitle: "ligula.",
    companyName: "Nec Enim Limited",
    ratePerHour: "$134",
    skills: ["XCD", "TND", "EUR", "INR", "RON", "AUD", "BBD", "SGD", "AMD"],
    email: "enim.gravida.sit@hotmail.edu",
  },
  {
    id: 49,
    jobTitle: "fringilla, porttitor",
    companyName: "Massa Non LLC",
    ratePerHour: "$101",
    skills: ["MYR", "MGA", "BRL", "EUR", "NOK", "ARS"],
    email: "sagittis@yahoo.com",
  },
  {
    id: 50,
    jobTitle: "fermentum fermentum",
    companyName: "In Industries",
    ratePerHour: "$138",
    skills: ["IMP", "PGK", "PYG", "SAR", "CHF"],
    email: "at.augue@outlook.com",
  },
  {
    id: 51,
    jobTitle: "sapien. Nunc",
    companyName: "Phasellus Foundation",
    ratePerHour: "$140",
    skills: ["EUR", "ARS", "TND", "GHS", "KZT", "JPY", "LKR", "HNL"],
    email: "aliquam@aol.org",
  },
  {
    id: 52,
    jobTitle: "enim. Nunc",
    companyName: "Auctor Quis Institute",
    ratePerHour: "$101",
    skills: ["ZAR", "KGS", "BRL", "KRW", "MOP", "DKK", "MNT", "DKK"],
    email: "proin.nisl@hotmail.ca",
  },
  {
    id: 53,
    jobTitle: "vel",
    companyName: "Tristique Aliquet Corporation",
    ratePerHour: "$112",
    skills: ["EUR", "FJD", "INR", "NIO", "GEL", "ZWD", "BMD", "JOD", "UYU"],
    email: "ligula.nullam@outlook.couk",
  },
  {
    id: 54,
    jobTitle: "vel",
    companyName: "Dapibus Rutrum Industries",
    ratePerHour: "$60",
    skills: ["KES", "TWD", "GTQ", "TTD"],
    email: "vitae.semper.egestas@hotmail.net",
  },
  {
    id: 55,
    jobTitle: "pede nec",
    companyName: "Scelerisque Neque Industries",
    ratePerHour: "$71",
    skills: ["HNL", "DKK", "USD", "SEK", "USD", "MGA", "MYR"],
    email: "ad.litora@protonmail.edu",
  },
  {
    id: 56,
    jobTitle: "ac mattis",
    companyName: "Ipsum Nunc Ltd",
    ratePerHour: "$122",
    skills: ["TND", "EUR", "GIP", "USD", "GBP", "KWD", "SEK"],
    email: "odio@yahoo.edu",
  },
  {
    id: 57,
    jobTitle: "erat",
    companyName: "Malesuada Malesuada Integer Inc.",
    ratePerHour: "$132",
    skills: ["LYD", "'MMK", "MKD", "MZN", "XAF", "UAH"],
    email: "mollis.lectus@google.couk",
  },
  {
    id: 58,
    jobTitle: "in faucibus",
    companyName: "Aliquam Tincidunt Consulting",
    ratePerHour: "$149",
    skills: ["BYN", "'CZK", "RON", "XAF"],
    email: "ultricies.dignissim.lacus@aol.net",
  },
  {
    id: 59,
    jobTitle: "risus.",
    companyName: "Gravida LLP",
    ratePerHour: "$74",
    skills: ["MRU", "NAD", "MWK"],
    email: "ligula.aenean.euismod@outlook.org",
  },
  {
    id: 60,
    jobTitle: "Nullam vitae",
    companyName: "Ligula Limited",
    ratePerHour: "$96",
    skills: ["ISK", "AOA", "DKK", "AED", "XCD", "EUR", "NAD", "IDR", "EUR"],
    email: "arcu.vivamus.sit@protonmail.net",
  },
  {
    id: 61,
    jobTitle: "lacus. Nulla",
    companyName: "Tortor Nibh Inc.",
    ratePerHour: "$131",
    skills: ["IQD", "EUR", "CHF", "KGS", "GEL", "GBP", "LBP", "AZN", "DZD"],
    email: "cras.convallis.convallis@protonmail.ca",
  },
  {
    id: 62,
    jobTitle: "erat. Vivamus nisi.",
    companyName: "Mi Pede Associates",
    ratePerHour: "$56",
    skills: ["CLP", "NAD", "LAK", "VEF", "EUR", "AOA", "USD"],
    email: "nam.porttitor@google.ca",
  },
  {
    id: 63,
    jobTitle: "ut",
    companyName: "Elit A Limited",
    ratePerHour: "$119",
    skills: ["BYN", "FJD", "XAF", "KGS", "LKR"],
    email: "blandit.enim@hotmail.org",
  },
  {
    id: 64,
    jobTitle: "non magna. Nam",
    companyName: "Dui Nec Corp.",
    ratePerHour: "$124",
    skills: ["EUR", "JPY", "BOB", "EUR", "TJS", "LBP"],
    email: "ultricies.ligula@google.ca",
  },
  {
    id: 65,
    jobTitle: "est, congue",
    companyName: "Ipsum Corp.",
    ratePerHour: "$53",
    skills: [
      "HNL",
      "IMP",
      "GYD",
      "SGD",
      "UZS",
      "JOD",
      "DZD",
      "MRU",
      "PLN",
      "LKR",
    ],
    email: "ipsum.suspendisse@google.ca",
  },
  {
    id: 66,
    jobTitle: "Duis a mi",
    companyName: "Lorem Eget Associates",
    ratePerHour: "$91",
    skills: ["VEF", "MDL", "ALL", "CNY", "UYU"],
    email: "velit@yahoo.couk",
  },
  {
    id: 67,
    jobTitle: "pellentesque massa lobortis",
    companyName: "Pede Sagittis LLP",
    ratePerHour: "$101",
    skills: ["'XOF", "MVR", "ISK", "KZT", "USD"],
    email: "enim.nisl.elementum@google.couk",
  },
  {
    id: 68,
    jobTitle: "Nunc ut erat.",
    companyName: "Blandit Congue Associates",
    ratePerHour: "$64",
    skills: ["COP", "GHS", "USD", "EUR", "BAM", "HNL", "QAR"],
    email: "amet.luctus.vulputate@yahoo.net",
  },
  {
    id: 69,
    jobTitle: "nec ipsum.",
    companyName: "Vivamus Rhoncus Donec Corp.",
    ratePerHour: "$113",
    skills: ["KGS", "CAD", "MNT", "RSD", "KES"],
    email: "vulputate.mauris@icloud.com",
  },
  {
    id: 70,
    jobTitle: "ultrices posuere",
    companyName: "Erat Vel Foundation",
    ratePerHour: "$108",
    skills: ["KHR", "PHP", "EUR", "NAD"],
    email: "sit.amet.nulla@icloud.couk",
  },
  {
    id: 71,
    jobTitle: "sociis natoque",
    companyName: "Orci Associates",
    ratePerHour: "$113",
    skills: [
      "BWP",
      "AMD",
      "USD",
      "EUR",
      "UZS",
      "GBP",
      "CNY",
      "'CZK",
      "AED",
      "HUF",
    ],
    email: "tempus.eu@google.org",
  },
  {
    id: 72,
    jobTitle: "at arcu.",
    companyName: "Arcu Sed Inc.",
    ratePerHour: "$122",
    skills: ["BYN", "PEN", "MUR"],
    email: "lacus.varius.et@yahoo.edu",
  },
  {
    id: 73,
    jobTitle: "non leo. Vivamus",
    companyName: "Sed Consulting",
    ratePerHour: "$64",
    skills: ["'EUR", "VND", "ZMW", "MOP", "PHP", "KES", "EUR", "CHF"],
    email: "vitae.sodales@yahoo.com",
  },
  {
    id: 74,
    jobTitle: "dolor.",
    companyName: "Eros Nec Inc.",
    ratePerHour: "$87",
    skills: ["KWD", "MOP", "EUR", "EUR", "XAF", "ZWD", "MWK"],
    email: "vivamus.sit.amet@outlook.com",
  },
  {
    id: 75,
    jobTitle: "Phasellus",
    companyName: "Diam Lorem Auctor Institute",
    ratePerHour: "$141",
    skills: ["XAF", "SAR", "HRK", "TTD"],
    email: "diam.pellentesque.habitant@outlook.org",
  },
  {
    id: 76,
    jobTitle: "ipsum dolor",
    companyName: "Nec Industries",
    ratePerHour: "$106",
    skills: ["SGD", "HRK", "EUR", "KWD", "KES", "MYR"],
    email: "at.augue.id@aol.edu",
  },
  {
    id: 77,
    jobTitle: "et netus",
    companyName: "Phasellus Nulla Integer Corp.",
    ratePerHour: "$84",
    skills: [
      "EUR",
      "'XOF",
      "NOK",
      "PLN",
      "DKK",
      "LYD",
      "UAH",
      "CAD",
      "KWD",
      "UGX",
    ],
    email: "nullam.vitae.diam@yahoo.org",
  },
  {
    id: 78,
    jobTitle: "luctus et",
    companyName: "Interdum Feugiat Limited",
    ratePerHour: "$121",
    skills: ["HKD", "DZD", "BRL", "XAF"],
    email: "integer.sem@outlook.net",
  },
  {
    id: 79,
    jobTitle: "Cras",
    companyName: "Eu Associates",
    ratePerHour: "$73",
    skills: ["DOP", "JMD", "NOK", "THB", "AED", "QAR"],
    email: "consectetuer.euismod@protonmail.com",
  },
  {
    id: 80,
    jobTitle: "sed,",
    companyName: "Risus Donec Egestas Foundation",
    ratePerHour: "$146",
    skills: ["AUD", "KGS", "KYD", "LKR", "MVR", "BGN"],
    email: "eleifend.cras@hotmail.com",
  },
  {
    id: 81,
    jobTitle: "arcu. Sed",
    companyName: "At Libero Foundation",
    ratePerHour: "$108",
    skills: [
      "GBP",
      "RUB",
      "MNT",
      "CHF",
      "INR",
      "EUR",
      "EUR",
      "LYD",
      "BGN",
      "EUR",
    ],
    email: "purus.nullam@aol.net",
  },
  {
    id: 82,
    jobTitle: "imperdiet non, vestibulum",
    companyName: "Eu Neque Foundation",
    ratePerHour: "$72",
    skills: ["EUR", "DOP", "TRY", "EUR", "'MMK", "EUR", "IQD", "'EUR", "LKR"],
    email: "montes.nascetur.ridiculus@outlook.edu",
  },
  {
    id: 83,
    jobTitle: "Donec tempus,",
    companyName: "Nec Urna LLP",
    ratePerHour: "$132",
    skills: ["USD", "SAR", "'XOF", "EUR", "GBP", "ALL", "XAF"],
    email: "mus.proin@google.org",
  },
  {
    id: 84,
    jobTitle: "Nulla",
    companyName: "Arcu Sed Et PC",
    ratePerHour: "$52",
    skills: ["ZMW", "SGD", "HKD", "BGN", "KHR", "GIP", "GTQ", "IDR"],
    email: "placerat.velit@icloud.com",
  },
  {
    id: 85,
    jobTitle: "Integer",
    companyName: "Condimentum Eget Volutpat Limited",
    ratePerHour: "$91",
    skills: ["EUR", "KGS", "HUF", "BWP", "MNT", "QAR", "MRU", "EUR"],
    email: "eu.enim@hotmail.couk",
  },
  {
    id: 86,
    jobTitle: "mus. Proin vel",
    companyName: "Nisl Quisque Foundation",
    ratePerHour: "$58",
    skills: ["TTD", "PYG", "INR", "HNL", "PKR"],
    email: "lectus.ante@protonmail.edu",
  },
  {
    id: 87,
    jobTitle: "imperdiet dictum magna.",
    companyName: "Lectus Justo Associates",
    ratePerHour: "$133",
    skills: ["KES", "TMT", "TWD"],
    email: "donec.tempor.est@yahoo.ca",
  },
  {
    id: 88,
    jobTitle: "massa. Mauris vestibulum,",
    companyName: "Magna Sed Dui Company",
    ratePerHour: "$71",
    skills: ["UGX", "AMD", "CRC", "MYR", "EUR", "XAF", "'EUR", "HUF"],
    email: "donec.luctus@protonmail.couk",
  },
  {
    id: 89,
    jobTitle: "Aliquam vulputate",
    companyName: "Morbi Tristique Incorporated",
    ratePerHour: "$109",
    skills: ["PLN", "EUR", "USD", "EUR", "XCD", "USD", "NZD", "RUB"],
    email: "mi.aliquam@protonmail.edu",
  },
  {
    id: 90,
    jobTitle: "magnis",
    companyName: "Non Luctus Sit Ltd",
    ratePerHour: "$115",
    skills: ["IQD", "EUR", "DOP", "TJS", "PLN"],
    email: "tristique.aliquet.phasellus@google.ca",
  },
  {
    id: 91,
    jobTitle: "orci, in",
    companyName: "Suspendisse Corp.",
    ratePerHour: "$81",
    skills: ["MXN", "CHF", "EUR", "RSD"],
    email: "integer@google.edu",
  },
  {
    id: 92,
    jobTitle: "felis,",
    companyName: "Dolor Vitae Limited",
    ratePerHour: "$75",
    skills: ["TJS", "NIO", "RUB", "SAR", "KHR", "LAK", "DOP", "EUR"],
    email: "id.risus@icloud.net",
  },
  {
    id: 93,
    jobTitle: "ut, sem.",
    companyName: "Pede Et Risus Ltd",
    ratePerHour: "$111",
    skills: ["GTQ", "MXN", "KGS", "EUR", "RUB", "EUR"],
    email: "non.feugiat@yahoo.net",
  },
  {
    id: 94,
    jobTitle: "rhoncus. Proin",
    companyName: "Justo Proin Non Institute",
    ratePerHour: "$124",
    skills: ["CRC", "EUR", "EUR", "IQD", "'CZK", "CLP"],
    email: "sagittis.lobortis@yahoo.org",
  },
  {
    id: 95,
    jobTitle: "elit, pretium et,",
    companyName: "Ullamcorper Nisl LLP",
    ratePerHour: "$84",
    skills: ["UYU", "EUR", "BYN", "KHR", "HRK"],
    email: "venenatis.lacus@protonmail.net",
  },
  {
    id: 96,
    jobTitle: "ut cursus",
    companyName: "Vivamus Nibh Ltd",
    ratePerHour: "$126",
    skills: ["GBP", "NGN", "CAD", "EUR", "SAR", "BHD", "AOA", "RSD", "UYU"],
    email: "pellentesque.tincidunt@aol.com",
  },
  {
    id: 97,
    jobTitle: "Quisque",
    companyName: "Consectetuer Rhoncus Nullam Inc.",
    ratePerHour: "$52",
    skills: ["BAM", "XOF", "DKK", "MUR", "RWF", "XCD", "XAF", "TND"],
    email: "purus.gravida@hotmail.ca",
  },
  {
    id: 98,
    jobTitle: "mus.",
    companyName: "Nullam Velit Company",
    ratePerHour: "$100",
    skills: ["NZD", "UAH", "TJS", "ISK"],
    email: "lectus@protonmail.net",
  },
  {
    id: 99,
    jobTitle: "interdum. Curabitur",
    companyName: "Erat Etiam Vestibulum Corp.",
    ratePerHour: "$105",
    skills: [
      "OMR",
      "MGA",
      "MXN",
      "VND",
      "CDF",
      "BMD",
      "MWK",
      "DKK",
      "EUR",
      "UGX",
    ],
    email: "magna.cras@yahoo.edu",
  },
  {
    id: 100,
    jobTitle: "at, velit.",
    companyName: "Per Inceptos Industries",
    ratePerHour: "$103",
    skills: [
      "MYR",
      "UYU",
      "ALL",
      "EUR",
      "'EUR",
      "JOD",
      "SZL",
      "PHP",
      "AOA",
      "CNY",
    ],
    email: "libero.est@google.couk",
  },
];
