export const UPDATE_LOGGED_IN_STATUS = "UPDATE_LOGGED_IN_STATUS";
export const UPDATE_LOGGED_IN_USER_DATA = "UPDATE_LOGGED_IN_USER_DATA";
export const UPDATE_JOBS_APPLIED_BY_FREELANCER =
  "UPDATE_JOBS_APPLIED_BY_FREELANCER";
